import Std

/-!
# Algebraic core for the real scalar Hardy endpoint construction

This file starts with the purely algebraic identities behind the rational
tails in the endpoint example.  The analytic PDE statements will depend on
these nodes later.

Completion status for every declaration is generated by
`scripts/generate_status.py`.
-/

namespace HardyCompactSupport

/-!
We use an indeterminate `z = s^2` and work with numerators after multiplying
by `(1 + z)^2`.  This avoids division-side conditions in the first layer.
-/

namespace AlgebraicIdentities

def RNRawNum (n k z : Int) : Int :=
  2 * k * (2 * k * z - n * z - n + 4 * z^2 + 6 * z)

def RNInfNum (k z : Int) : Int :=
  8 * k * (1 + z)^2

def RNSubInfNumTarget (n k z : Int) : Int :=
  2 * k * ((2 * k - n - 2) * z - (n + 4))

def RDExtraNum (k z : Int) : Int :=
  4 * k * (1 + z)

def RDSubInfNumTarget (n k z : Int) : Int :=
  2 * k * ((2 * k - n - 4) * z - (n + 6))

def IsLinearInt (f : Int → Int) : Prop :=
  ∃ a b : Int, ∀ z : Int, f z = a * z + b

/-- NODE HE.AlgebraicIdentities.RN.sub_inf_num
deps:
statement: numerator form of `R_N(z) - 8 k`.
-/
theorem RN_sub_inf_num (n k z : Int) :
    RNRawNum n k z - RNInfNum k z = RNSubInfNumTarget n k z := by
  unfold RNRawNum RNInfNum RNSubInfNumTarget
  grind

/-- NODE HE.AlgebraicIdentities.RD.sub_inf_num
deps: HE.AlgebraicIdentities.RN.sub_inf_num
statement: numerator form of `R_D(z) - (8 k - 4)`.
-/
theorem RD_sub_inf_num (n k z : Int) :
    RNRawNum n k z - RNInfNum k z - RDExtraNum k z = RDSubInfNumTarget n k z := by
  unfold RNRawNum RNInfNum RDExtraNum RDSubInfNumTarget
  grind

/-- NODE HE.AlgebraicIdentities.RN.tail_degree
deps: HE.AlgebraicIdentities.RN.sub_inf_num
statement: after cancellation of the quadratic term, the numerator is linear in `z`.
-/
theorem RN_tail_degree (n k : Int) :
    IsLinearInt (fun z => RNRawNum n k z - RNInfNum k z) := by
  refine ⟨2 * k * (2 * k - n - 2), -2 * k * (n + 4), ?_⟩
  intro z
  change RNRawNum n k z - RNInfNum k z =
    2 * k * (2 * k - n - 2) * z + -2 * k * (n + 4)
  rw [RN_sub_inf_num]
  unfold RNSubInfNumTarget
  grind

/-- NODE HE.AlgebraicIdentities.RD.tail_degree
deps: HE.AlgebraicIdentities.RD.sub_inf_num
statement: odd-profile tail also has linear numerator after cancellation.
-/
theorem RD_tail_degree (n k : Int) :
    IsLinearInt (fun z => RNRawNum n k z - RNInfNum k z - RDExtraNum k z) := by
  refine ⟨2 * k * (2 * k - n - 4), -2 * k * (n + 6), ?_⟩
  intro z
  change RNRawNum n k z - RNInfNum k z - RDExtraNum k z =
    2 * k * (2 * k - n - 4) * z + -2 * k * (n + 6)
  rw [RD_sub_inf_num]
  unfold RDSubInfNumTarget
  grind

end AlgebraicIdentities
end HardyCompactSupport



